[package]
name = "lolxd-bot"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9"
markov = {git = "https://github.com/saethlin/markov", branch="stable", default-features=false, features=["hashbrown"]}
openssl = { version = "0.10", features = ["vendored"] }
websocket = "0.21"
structopt = "0.2"
